### ISSUE TITLE
Captcha is broken

### ISSUE THREAD

**Issue by zackhall** [jquery/jqueryui.com#144]
I went to file a jquery UI bug, but was prompted with a captcha whose image will not load. Because of this, I cannot solve the captcha and I'm blocked from creating a bug. 

![image](https://cloud.githubusercontent.com/assets/1725349/13444711/ae4e8b08-dfbc-11e5-8179-d6941ff0cbb2.png)

**Comment by zackhall** [comment]
Here is the issue I'm trying to open on jQuery UI:

# Datepicker tests failed on Leap Day

The following two test failures were picked up by the MSFT Edge team on leap day: Feb 29th, 2016. 

**datepicker: options: defaultDate**

Asserts Passed:14/16 Failure: {message: Default date -2y, expected: "Sat Mar 01 2014 00:00:00 GMT-0800 (Pacific Standard Time)", actual: "Fri Feb 28 2014 00:00:00 GMT-0800 (Pacific Standard Time)", source: at TestHelpers.datepicker.equalsDate (http://protractor/TestContent/JQueryUI/1.11.4/tests/unit/datepicker/datepicker_test_helpers.js:15:3) at Anonymous function (http://protractor/TestContent/JQueryUI/1.11.4/tests/unit/datepicker/datepicker_options.js:324:2)} Failure: {message: Default date +1 Y, expected: "Wed Mar 01 2017 00:00:00 GMT-0800 (Pacific Standard Time)", actual: "Tue Feb 28 2017 00:00:00 GMT-0800 (Pacific Standard Time)", source: at TestHelpers.datepicker.equalsDate (http://protractor/TestContent/JQueryUI/1.11.4/tests/unit/datepicker/datepicker_test_helpers.js:15:3) at Anonymous function (http://protractor/TestContent/JQueryUI/1.11.4/tests/unit/datepicker/datepicker_options.js:329:2)} 

**datepicker: options: setDate**

Asserts Passed:22/24 Failure: {message: Set date - +2y, expected: "Thu Mar 01 2018 00:00:00 GMT-0800 (Pacific Standard Time)", actual: "Wed Feb 28 2018 00:00:00 GMT-0800 (Pacific Standard Time)", source: at TestHelpers.datepicker.equalsDate (http://protractor/TestContent/JQueryUI/1.11.4/tests/unit/datepicker/datepicker_test_helpers.js:15:3) at Anonymous function (http://protractor/TestContent/JQueryUI/1.11.4/tests/unit/datepicker/datepicker_options.js:539:2)} Failure: {message: Set date inline - +2y, expected: "Thu Mar 01 2018 00:00:00 GMT-0800 (Pacific Standard Time)", actual: "Wed Feb 28 2018 00:00:00 GMT-0800 (Pacific Standard Time)", source: at TestHelpers.datepicker.equalsDate (http://protractor/TestContent/JQueryUI/1.11.4/tests/unit/datepicker/datepicker_test_helpers.js:15:3) at Anonymous function (http://protractor/TestContent/JQueryUI/1.11.4/tests/unit/datepicker/datepicker_options.js:568:2)}

**Comment by scottgonzalez** [comment]
We're working on the CAPTCHA issue. We're missing a dependency that's used to render the image.

**Comment by zackhall** [comment]
Thanks for the update @scottgonzalez! Can you update here when it's resolved so that I can open the bug above in your bug base? :+1:

**Comment by scottgonzalez** [comment]
Of course. Once the issue is fixed, we'll let you know here and close the issue.

**Comment by scottgonzalez** [comment]
This should be working now. If you run into a problem again, just let us know and we'll reopen this, but I don't anticipate any problems at this point.

**Comment by zackhall** [comment]
Still seeing issues. Seeing this error no matter how many times I click the "I'm not a robot" box and submit.

![image](https://cloud.githubusercontent.com/assets/1725349/13477303/a8b7febc-e080-11e5-81db-6546d4fc3bea.png)

**Comment by scottgonzalez** [comment]
Ok, I've notified our infrastructure team that this still isn't working properly.

**Comment by zackhall** [comment]
Thanks, @scottgonzalez! Much appreciated.

**Comment by scottgonzalez** [comment]
Can you try again now?

**Comment by zackhall** [comment]
Same thing, still. 

On Windows, with both Microsoft Edge and Chrome it fails with the "Captcha failed to handle original request" error.

**Comment by scottgonzalez** [comment]
This time you were hitting https://trac.edgewall.org/ticket/12379 (congrats on uncovering a new bug in Trac's spam filter :smile:). Can you try again?

**Comment by scottgonzalez** [comment]
Closing due to inactivity. If you're still having issues, please just leave another comment and we'll reopen.

**Comment by zackhall** [comment]
Hi @scottgonzalez, thanks for following up. This just fell of my radar but I can confirm the bug is fixed and I have filed the original bug: https://bugs.jqueryui.com/ticket/14942

Much appreciated!

**Comment by scottgonzalez** [comment]
Great! Thanks for filing the issue.
