### ISSUE TITLE
Deployment setup is broken

### ISSUE THREAD

**Issue by mgol** [jquery/jqueryui.com#156]
There are two issues:

1. `grunt deploy` doesn't work at all in Node 4 or newer because, as @Krinkle discovered, it uses an obsolete [`node-syslog`](https://www.npmjs.com/package/node-syslog) package; it needs to be changed to [`modern-syslog`](https://www.npmjs.com/package/modern-syslog).
2. It doesn't work in Node 0.12 for different reasons; it produces a weird message about Grunt 0.4.5 missing even though it's installed:
```
$ grunt deploy        
Running "check-modules" task

Running "clean-dist" task

Running "build-posts:page" (build-posts) task
Built 107 pages.

Running "build-resources:all" (build-resources) task
Built 140 resources.

Running "build-download" task
Initializing download module, might take a while...
>> Running "check-modules" task
>> >> Error: npm ERR! missing: grunt@0.4.5, required by download.jqueryui.com@2.1.10
>> Warning: Task "check-modules" failed. Use --force to continue.
>> Error: Task "check-modules" failed.
>>     at Task.<anonymous> (/Users/mgol/Documents/projects/public/jquery/jqueryui.com/node_modules/grunt/lib/util/task.js:205:15)
>>     at null._onTimeout (/Users/mgol/Documents/projects/public/jquery/jqueryui.com/node_modules/grunt/lib/util/task.js:241:33)
>>     at Timer.listOnTimeout (timers.js:119:15)
>> 
>> Aborted due to warnings.
>> 
Warning: Command failed: /bin/sh -c grunt prepare --stack
 Use --force to continue.
Error: Command failed: /bin/sh -c grunt prepare --stack

    at ChildProcess.exithandler (child_process.js:754:12)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1019:16)
    at Socket.<anonymous> (child_process.js:1190:11)
    at Socket.emit (events.js:107:17)
    at Pipe.close (net.js:484:11)

Aborted due to warnings.
```

**Comment by mgol** [comment]
The first point should be then extracted to a separate issue, shouldn't it?

**Comment by scottgonzalez** [comment]
That would be part of download.jqueryui.com, which I believe has other issues with 4+, though they may have been resolved. For syslog specifically, it should be as simple as just updating the `simple-log` dependency from `1.2.0` to `1.3.0`. I can do that now and it'll go live with the jQuery UI 1.12.1 release.

**Comment by scottgonzalez** [comment]
https://github.com/jquery/download.jqueryui.com/commit/4d88de50368f398b714c666283e1dd44ec04f4f5

**Comment by mgol** [comment]
Is there anything else that's broken? The page at https://jqueryui.com/browser-support/ still doesn't contain current data.

**Comment by scottgonzalez** [comment]
Well, we just haven't deployed. We're hopefully doing the 1.12.1 release this week, which is when download builder and the web sites will be deployed.

**Comment by scottgonzalez** [comment]
@mgol All of the jQuery UI sites have been deployed now.
